### ISSUE TITLE
Allow characters to specify they have a sound per combo size

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#103]
Essentially, similar to how "per_chain" functions, this would allow creators to specify voicelines for different combo sizes. 
To demonstrate, "combo4" would play with a +4 combo, and "combo_echo6" would play with a +6 shock panel combo.

**Comment by MizunoKetsuban** [comment]
To add to this, the "classic" style should be adjusted so that "combo_echo" always plays regardless of the amount of shock panels.

**Comment by Endaris** [comment]
Suggestion for more flexibility and clear naming:
Don't call it per_combo, call it something like combo_echo_panel_threshold, set the default to 6 and play the sound whenever the amount of panels in a shock match is >= the variable.
We should reserve per_combo for the off chance that we ever want to support distinct sounds for distinct combo sizes like in per_chain.

**Comment by MizunoKetsuban** [comment]
Except that is actually what I'm asking for. Being able to delay the echo would simply be a byproduct of the functionality.
