### ISSUE TITLE
Implement garbage queue "telegraph" 

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#11]
As of opening this issue, it had 69 votes (most voted issue having 72)

**Comment by jon12156** [comment]
Note: I have a few branches here related to telegraph:

https://github.com/panel-attack/panel-attack/tree/garbage-system-changes 
beginnings of telegraph, kinda almost totally working in single player

branched from the above:
https://github.com/panel-attack/panel-attack/tree/telegraph-netplay
start of trying to get telegraph to work on 2 player

https://github.com/panel-attack/panel-attack/tree/back-to-basics-garbage-netplay
after having borked netplay completely, I started pulling back most of the original recv_garbage code and garbage dropping (still doesn't work)

and finally:
https://github.com/panel-attack/panel-attack/tree/simulate-foreign-player
attempting a new way of doing netplay, where we don't wait for inputs from the other player, we simulate their stack based on what their last input state was, and roll back to correct it if we ended up being wrong.
I will continue to develop this last branch on my own fork:
https://github.com/jon12156/panel-attack/tree/simulate-foreign-player

**Comment by jon12156** [comment]
New branch:
https://github.com/panel-attack/panel-attack/tree/telegraph-netplay-2019-09-27

This is a branch with telegraph working (not perfectly) with 2p local vs.
based off this one: https://github.com/panel-attack/panel-attack/tree/telegraph-netplay

with latest changes from master as of today.

**Comment by JamesVanBoxtel** [comment]
https://github.com/panel-attack/panel-attack/tree/telegraphAlpha

Is the latest branch updated off of the alpha.

- [x] 2 player telegraph needs to show up on the right side
- [x] Lots of unused code needs to be removed or used
- [x] rollback needs to be implemented for net play
