### ISSUE TITLE
All json reading functions should have better handling

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#110]
Anywhere we call json.decode we should output there was an error in the JSON file and write out the file name.

**Comment by AegisCrusader** [comment]
Interestingly enough, the PA Toolkit actually did this... maybe I can recreate it here.

**Comment by JamesVanBoxtel** [comment]
I think the method may actually return nil on an error, we just don't do anything to catch the problem

**Comment by AegisCrusader** [comment]
> I think the method may actually return nil on an error, we just don't do anything to catch the problem

for now that's probably the best way to go, though in the future it would be nice to notify of who it is as well.

**Comment by Endaris** [comment]
All locations where json is being read have been replaced with FileUtils.readJsonFile(file)
