### ISSUE TITLE
Create support for 1P Vs Health Attack Engine

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#121]
Add a story mode to the game where you fight characters in succession.

We should support difficulties from beginner all the way to master level players. Probably have to unlock the later ones.

We are thinking we can use a "health" system, where you must send enough garbage at the opponent to make them lose, meanwhile they will send preprogrammed attacks back at you.

**Comment by Endaris** [comment]
Suggestion to rename this issue to something like "1p vs healthbar based attack engine" as a working issue title, just to separate the concern of writing a story and entering lore transitions and what not into the game and the raw functionality for the stack.

**Comment by Endaris** [comment]
This is on beta and looking good as a first version.
We'll iterate on details.
