### ISSUE TITLE
Dynamic music lacks fade for player 1 online

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#125]
When playing online, the dynamic music has a bug where when the music switches between normal and danger specifically on player 1's side, the music switches instantly instead of fading. It operates as intended if player 2 is the one to switch the music.

**Comment by Endaris** [comment]
Also reproducable in 2p vs local

**Comment by Endaris** [comment]
System for music playback has been completely overhauled, can no longer reproduce
