### ISSUE TITLE
"Random colors" option in puzzles revision

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#126]
I feel like the "random colors" option in puzzle mode needs some adjustments.
Namely, it should randomize every time you _clear_ a puzzle, not every time you _fail_ a puzzle.
It additionally fails to cycle colors 6 and 7 into the mix. Though granted, it should only attempt to do so if it detects those colors are present in the original puzzle to begin with.

**Comment by Endaris** [comment]
On my end color 6 gets cycled properly with everything else and 7 gets cycled as well if it is present in the original puzzle.
Can you recheck this please?
I definitely agree on the puzzle only randomizing once for each series of attempts, looking into that.
