### ISSUE TITLE
Make combo_echo play regardless of shock panel amount

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#127]
I feel like the majority of people are in agreement with this. Shock panels are already uncommon enough as it is, and this shouldn't be too hard to implement.

**Comment by Endaris** [comment]
I generally agree with the sentiment but we might still want to throw out a survey for this to confirm this impression.
Due to the general rarity of the SFX and the high possibility that people might not even know about this file, I suggest including a paragraph at the bottom of the survey that explains how combo_echo works.
Suggestion for that section:

> `combo_echo` is a sound effect for characters that is played in PdP/TA when a character performs a combo with more than 5 shock panels in it, characteristically sounding like a recording of the regular combo SFX being spoken into a metal container. In successive adaptions such as PPL, this type of sound plays for any match or combo that has shock panels in it, serving as a consistent audio cue for incoming shock garbage. Due to +6/+7 shock combos being extremely rare, this SFX is seldomly played in Panel Attack and in the majority of cases there is no audio cue when shock garbage is being sent. For this reason it has been proposed to divert from the originals and use the more logical approach from PPL for Panel Attack.

**Comment by MizunoKetsuban** [comment]
Where do you propose this survey would be posted?

**Comment by Endaris** [comment]
In the #surveys channel on the discord.

**Comment by MizunoKetsuban** [comment]
It'll need to be done by someone who can actually post in that channel, then. Because if I could, I would.

**Comment by Endaris** [comment]
Discussion after poll result: https://discord.com/channels/196674532491132937/854285957347147778/1000279509200814120
Make it possible to provide sounds for different sizes as suggested in panel-attack/panel-game#103 to satisfy both sides.
We'd have to look out for backwards compatibility and new naming scheme though so I'm going to remove the good first issue label for now.
