### ISSUE TITLE
Server replays don't save the engine version into the file

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#130]
(it is put in the file name however...)

**Comment by Endaris** [comment]
This might be a necessary step before sceneRefactor so the compatibility loading of the new replay format does not stumble over its own feet when it comes to server replays.

**Comment by Endaris** [comment]
This is implemented but still needs to be deployed, will try to read up and find a calm period where I don't disturb matches.

**Comment by Endaris** [comment]
Has been deployed and seems to be working
