### ISSUE TITLE
XBox One Series X: Controller buttons malfunctioning in menus

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#138]
Reported by WatsyWoo#5979
They are using an XBox One Series X controller.

In the menu, specifically in character select, button presses are interpreted on both press and release, meaning that tapping the B swap puts cursor on "Leave" for pressing down and leaving the room upon release. 
It occurs in the main menu as well.
Notably, pressing down the button bound to the A swap has the same results as pressing the B swap, forcing the user to navigate the menu using keyboard.

> The menus seem to be the only thing with the issue. If I press A or B it will switch the selection to the quit/leave option on the screen. If I let go it will exit. But if I let it go after moving the cursor to another menu item it will select that menu item

DPad inputs are working as expected in the menus.

Once a game has been started, button inputs are working as expected.

Input config:
![grafik](https://user-images.githubusercontent.com/22120694/178634408-e7582a1b-0381-4043-b97b-a972671604b0.png)

**Comment by JamesVanBoxtel** [comment]
worth retesting after Sankyrs twig lands

**Comment by Endaris** [comment]
Given how old this is and how we learned about how Steam for instance can completely mess with your controller inputs, I'm actually more inclined to close this. We haven't heard any alike reports since then and I don't think this type of controller is *that* rare.
