### ISSUE TITLE
Chain/combo card opacity option

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#139]
Exactly what it says on the tin. Would operate similarly to the portrait darkness option. This also has precedent from the official games which often let you choose whether they're solid or "transparent"

**Comment by JamesVanBoxtel** [comment]
This is on my list of things I want to do

**Comment by JamesVanBoxtel** [comment]
This is fixed in beta. We currently don't allow you to change the setting. If we get feedback in discord we can change that.
