### ISSUE TITLE
Pop FX rotation is buggy

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#140]
The readme documents the property as popfx_rotation but it is popfx_burstRotate in the code and then the code uses it as popfx_burstRrotate so it is always false.

Also the rotations seem wrong, seems all 8 directions should be rotated equally.

Lots of global cleanup and redundant code we can fix while we are at it.

**Comment by Endaris** [comment]
Fixed by panel-attack/panel-attack#1156
