### ISSUE TITLE
Add touch controls as input

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#160]
Original discussion: https://discord.com/channels/196674532491132937/854285957347147778/936037447962333184
Potentially problematic for gamebalance due to the ability to teleport your cursor to where you need it, enabling a completely different metagame for chain and combo building by using your time elsewhere while waiting for inserts and other stuff.

**Comment by jon12156** [comment]
I'm working on this.  As far as game balance is concerned, we may never allow ranked matches of controller vs touch.

See branch "touch-controls"

**Comment by JamesVanBoxtel** [comment]
main branches now support touch engine, just need to bring over the rest of the touch UI to beta

**Comment by Endaris** [comment]
Touch has been "in the game" in regards to engine, input method and server for a long time now, only missing stuff is suitable UI which is entirely documented in issues between
- panel-attack/panel-game#143 
- panel-attack/panel-game#427 

Closing.
