### ISSUE TITLE
Default panels show up in matches even when you remove them and have other panels in your panels folder

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#163]
The default panels shouldn't be used if you have other panels in your panels folder, just like the default characters are only added in if you don't have characters.

**Comment by AegisCrusader** [comment]
Are the default panels disabled or deleted in this case?

**Comment by JamesVanBoxtel** [comment]
Deleted. As in not in the user data directory.

**Comment by JamesVanBoxtel** [comment]
We should do like puzzles where we copy them over to the user data folder only  it's empty. And then only match to panels in the user data dir

**Comment by AegisCrusader** [comment]
Probably.
