### ISSUE TITLE
Room initialization failure when you’ve had a ton of games

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#164]
Server side? Happened to both players and the spectator

Needs investigation.

**Comment by AegisCrusader** [comment]
Where was this seen?

**Comment by AegisCrusader** [comment]
Oh, as in logging a room init failure somewhere. Yea, I can take this on.

**Comment by AegisCrusader** [comment]
Though this would definitely be something that should be logged server-side if we can, so I'm gonna label it as such.

**Comment by JamesVanBoxtel** [comment]
Sorry. Log should not have been in the title. I saw this a couple days ago in a long match with ruiii and someone else I think. It seems the more games in a set you play the more likely the whole room crashes.

**Comment by AegisCrusader** [comment]
I really haven't ever had this happen to me to be totally honest with ya, it might be because of poor internet connections or something but I've gone in excess of 100+ matches with a single user and not had a single problem

**Comment by JamesVanBoxtel** [comment]
It may not have to do with number of games. Could be the players just disagree on who won. If one player thinks the game is over they will wait for room initialization and if that fails they will exit out.

**Comment by AegisCrusader** [comment]
I'm willing to write this up to just "bad internet" when it happens now.

**Comment by JamesVanBoxtel** [comment]
Closing for now until we have reproducible steps
