### ISSUE TITLE
Leftover time can get really big if you leave focus especially on android

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#171]
The catching up bug is the result of leaving the app in the background from any position of the game whether through pausing, main menu, options menu, spectating, anything really. Now with that bug active, I dont know what it does to make the battle I am spectating slow and preventing you from leaving when trying to back out

**Comment by AegisCrusader** [comment]
Did this start because of the auto-pause? Maybe we just don't do auto-pause for android.

**Comment by JamesVanBoxtel** [comment]
I think it could be a change I made to leftover time but IDK. I gave Kudo all the details and they are looking into it.
