### ISSUE TITLE
Randomly mouse clicking the menus won't work all the time

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#175]
When you launch the game every once in a while the click menus don't work well with mouse clicking.

Sometimes you can click and sometimes you can't.

If it doesn't reproduce, restart the game and try again, happens like 1 /5th of app launches

**Comment by AegisCrusader** [comment]
When you say "Don't work well" do you mean that it doesn't click, no matter how many times you click the button?

**Comment by JamesVanBoxtel** [comment]
Like it works 1 / 5 times or so

**Comment by JamesVanBoxtel** [comment]
Haven't been able to reproduce lately, closing
