### ISSUE TITLE
Too much lag should not crash the game

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#176]
It should display the error message and then wait for a key to be pressed after a minimum delay, then go back to the lobby.

**Comment by AegisCrusader** [comment]
I do want to note that generally the user who gets this crash message is the user at fault, so I would recommend telling said user to ensure their internet connection is stable, I do not think we should give the opponent as a possibility for the error. However, we could do some testing to ensure this.

**Comment by JamesVanBoxtel** [comment]
This is now fixed in alpha
