### ISSUE TITLE
Player rating isn't shown in the lobby

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#18]

**Comment by sith-lord-of-git** [comment]
is it cool that I try to tackle this one?

**Comment by sith-lord-of-git** [comment]
@LittleEndu do you mean the current player rating or the ratings of the players in the rooms? I'll try to add ratings to the end of everyone's names.

**Comment by LittleEndu** [comment]
Basically everywhere where there's a player name there should also be their rating. Maybe not only while playing casual.
