### ISSUE TITLE
Useless getSupported("canvas") calls

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#19]
They are unnecessary (and didn't do anything to begin with after being introduced in our 11.2 update)

**Comment by JamesVanBoxtel** [comment]
We use this to know if we can go fullscreen? I'm assuming that's useful for mobile?

**Comment by JamesVanBoxtel** [comment]
IDK what I was talking about before but apparently I deleted these calls and this can be closed.
