### ISSUE TITLE
Implement automatic updates

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#2]
Jon said he already found a tutorial for it so I think he is working on it.

As of opening this issue, it had 72 votes, more than any other issue

**Comment by jon12156** [comment]
I'm not working on this yet.  

Here is the forum post and article I found:
https://love2d.org/forums/viewtopic.php?t=80788
https://github.com/adnzzzzZ/blog/issues/6

**Comment by jon12156** [comment]
We also have the option to update the game the way @sharpobject has done it for his other LÖVE game "Sword Girls"
That repo is here: https://github.com/sharpobject/sgre

**Comment by jon12156** [comment]
@bastnt has implemented this recently.
