### ISSUE TITLE
Enable alternative win conditions

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#206]
The goal is to rewrite / reflow the engine in a way that the win condition can be altered quite easily, enabling the development of custom gamemodes in the long term.
Currently, demanded custom game modes are near unimplementable due to the game being very focused on the standard game over condition, to a degree that the puzzle implementation is fairly ugly and further implementations would only make the game increasingly complex.

In essence, this issue is a requirement for:
panel-attack/panel-game#155 Redemption Mode
panel-attack/panel-game#71 Line Clear Mode
panel-attack/panel-game#121 Battle against healthbar based attack engine
panel-attack/panel-game#146 Time Attack Vs
panel-attack/panel-game#202 Instruction mode

and potentially other single/multiplayermodes we aren't thinking about right now.

**Comment by JamesVanBoxtel** [comment]
Adding high priority as a good architecture for this is important for all future features.

**Comment by Endaris** [comment]
Elaborating on the core issue with this.
Right now we have more than one competing mechanisms for ending the game.
Way 1 to end the game:
The stack prompts `Stack.game_ended` inside its `run` routine. This is game mode specific and ends the game by virtue of "the stack just stops running", rather than terminating.

Way 2 to end the game:
The stack runs into `Stack.set_game_over` one or the other way. This is game mode inspecific and ends the game by virtue of setting the `game_over_clock` property of the stack which in turn may get read by `game_ended` to determine the end of the game. However this is not mandatory and for puzzles for instance, the engine specifically relies on the stack *not* going game over as otherwise the game will brick. Due to this, the `Stack.simulate` code is somewhat littered with `self.match.mode ~= "puzzle"` conditions in order to stay in the expected state.
I'm not even sure why it bricks in the first place

Ideally, the win/loss condition should be managed inside a single method, including the classic game over one.
Game end should behave the same results on the stack table for all 1p variations.
