### ISSUE TITLE
Turn on / off ability to be challenged by an opponent while not actively waiting in the lobby

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#211]
and receive a notification during gameplay if you have been challenged.

This is mainly an issue with going through screens while keeping the lobby status in the background and then returning back to lobby so with a proper separation of concerns this might be much more doable after panel-attack/panel-attack#583 has hit beta.

**Comment by JamesVanBoxtel** [comment]
Renaming this to indicate you should be able to both play 1 player games and spectate etc while still being able to be challenged if you so choose. Also the opposite, you should be able to stay in the lobby but not be able to take challenges if you are just watching

**Comment by Endaris** [comment]
Closing as duplicate in favor of the better documented panel-attack/panel-game#308
