### ISSUE TITLE
You may also look for issues on this google sheet:

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#23]
Google Sheet with more issues:
https://docs.google.com/spreadsheets/d/1fJ1Mr29lVNW_AHEtSgmrqjdc1o83NFN5xjgs6rw3vjo/edit#gid=0

Not all of the issues on the google sheet have been turned into actual issues on Github yet, and community members may add to the google sheet from time to time.

If you see an issue on the google sheet that is already an issue here on github, feel free to delete it from the google sheet.

**Comment by JamesVanBoxtel** [comment]
We should probably go through this sheet and just make sure everything is moved over to here.

**Comment by Endaris** [comment]
Moved everything over, referenced on the sheet where I moved the things (or why not if I didn't)
