### ISSUE TITLE
Game freezes at reconnect when trying to catch up to long matches as a spectator

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#237]
Trying to spectate games upwards of 10min at the very least causes people to instantly disconnect from the server and then freeze at the "Connect..." message.

As reported by kornflakes recently, when pressing Ctrl+C in that screen, the game error'd out at line 244 in input.lua 
`stacks["P2"] = P2:toPuzzleInfo()`.
In spite of nil-checking P2, the function did not exist on the table, causing a crash at the end.
This may be a lead as there is apparently an incomplete stack table or maybe even a completely different table getting written into P2 in that scenario.

**Comment by AegisCrusader** [comment]
I'm wondering if the game is failing to start it is unable to send the entire game over a single TCP Packet. (I do not have any evidence for this, it's just a theory). If this theory is true, panel-attack/panel-attack#684 will be able to mitigate this.

**Comment by Endaris** [comment]
Closing until reconfirmed on canary
