### ISSUE TITLE
Attack Pattern dumps incorrectly

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#243]
Reported by chaos [here](https://discord.com/channels/196674532491132937/362093490538020864/1024845168718925894).

For reproducing/debugging:
[Replay that was dumped from](https://cdn.discordapp.com/attachments/362093490538020864/1024845167682932847/v046-2022-09-20-02-51-42-chaos952-L8-vs-Sankyr-L8-Casual-P1wins.txt)
[Dump for Player 1](https://cdn.discordapp.com/attachments/362093490538020864/1024845168060399726/dumpAttackPattern1.json)
[Dump for Player 2](https://cdn.discordapp.com/attachments/362093490538020864/1024845168416919603/dumpAttackPattern2.json)

According to chaos' observations, the dump for player 1 is incorrect, already visible in the first minute of the game when comparing the replay and playing the attack pattern.

**Comment by Endaris** [comment]
I have to admit that I never rechecked whether it was a problem with the dump or a problem with the playback.
@JamesVanBoxtel is this getting solved by panel-attack/panel-attack#737 ?

**Comment by JamesVanBoxtel** [comment]
Yes this is most likely the same problem. about 20 seconds in they both start doing combo chains, which both attack on the same frame.
