### ISSUE TITLE
Certain character crashes when combo_echo would be played

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#244]
This is specific to the [Puyo Ringo Jpn mod](https://discord.com/channels/196674532491132937/362093490538020864/1009475690753695824) (link leads to the message that has the upload, so it's safe to click).
Upon performing a +6/+7 shock combo that would play combo_echo, the game crashes. I could reproduce this.
[Shock Puzzle for reprodution](https://cdn.discordapp.com/attachments/362093490538020864/1009361671833264198/Shock_Test.txt)

combo_echo is not mandatory and there are many characters lacking that SFX that work just fine with it (playing a regular combo SFX instead).

**Comment by JamesVanBoxtel** [comment]
@Endaris is this fixed now?

**Comment by Endaris** [comment]
It doesn't crash anymore, nope, however there seem to be loading issues in puzzle mode where sounds won't play if the shock puzzle is restarted. I will investigate that further once I have my laptop back, will keep this open until then as a reminder.

**Comment by Endaris** [comment]
> It doesn't crash anymore, nope, however there seem to be loading issues in puzzle mode where sounds won't play if the shock puzzle is restarted. I will investigate that further once I have my laptop back, will keep this open until then as a reminder.

Didn't actually have anything to do with puzzle mode.
This character doesn't crash anymore so closing this.
There's a new issue for the other issues found with this character at panel-attack/panel-game#279 
The original reason was likely the same: For lack of a regular combo file, combo_echo probably *thought* it had a default combo SFX to fall back on but really didn't.
