### ISSUE TITLE
add support for mobile

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#25]
at least basic tapping and gestures to enable one to set up a bluetooth controller on a mobile device

**Comment by jon12156** [comment]
I suppose we also need a way for them to input their username

**Comment by jon12156** [comment]
maybe we make it as simple as recognizing they are on a mobile device (I imagine that's possible) and have that take them straight to input setup

**Comment by jon12156** [comment]
Oh sweet.  You can use love.keyboard.setTextInput to show the native system virtual keyboard on touch devices.
And https://love2d.org/wiki/love.touch exists.

**Comment by JamesVanBoxtel** [comment]
I think this is done and can be closed?

**Comment by Endaris** [comment]
Yes, for any further work regarding mobile we'll want to get some feedback from the actual mobile users (aka Poke, maybe Legshot) and then create new issues.

**Comment by Endaris** [comment]
I put up a thread for further feedback on the current Android builds and will open new issues for more specific feedback since general mobile support on client side already exists.
