### ISSUE TITLE
touch-controls branch - game currently assumes all stacks will be using touch, not a controller.

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#257]
we need to:
-create menu items to let the user select whether they will be using touch or controller as their input method.
This should possibly be in the character select menu. and each 1P mode.  At the very least, it could be added to the options menu off the main menu.  I will probably do it this way for now because character select will be revamped soonish.
-communicate the selection to the server to be relayed to opponents online.

Note: until we actually make use of love.touch instead of love.mouse  I don't think it will be practical to play 2p local with just touch-controls.  I believe love.touch will support multi-touch where love.mouse does not. Perhaps we manually specify P2 in local vs will be using controller.  I think we will still only ever support a single touch per stack.  multi-touch would however also let us press raise and swap panels at the same time, which IS supported by the network protocol I put together.

**Comment by JamesVanBoxtel** [comment]
I think this is fixed now on the touch branch?

**Comment by jon12156** [comment]
Yes
________________________________
