### ISSUE TITLE
portrait-mode branch - window resize behavior issues

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#259]
we can also push these changes to touch-controls:
on PC, if you want to use portrait mode, you may need to select it, select it again to disable, and select it once more, to get a semi-decently sized scale.  Let's fix this.  We should also ideally be able to resize the window on PC.
Make sure changes here don't break the functionality on android

**Comment by Endaris** [comment]
Portrait mode in its past form is not being maintained.
