### ISSUE TITLE
Player stacks should be in arrays, remove P1, P2

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#262]
Spread throughout the code is global variables P1 and P2.

Instead the match should have an array of players and access them locally via their index.

Not only will this be cleaner but make working with variable number of players better.

**Comment by Endaris** [comment]
All remaining uses of P1/P2 as globals have been purged.
P1 and P2 have still been made available as fields on match for convenience in porting from global to scoped access and alternatively the stacks are also available for access via the `Match.stacks` array, meaning all references to `match.P1` can be replaced with `match.stacks[1]`.

**Comment by Endaris** [comment]
Done
