### ISSUE TITLE
Game crashes after watching replays for long enough

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#265]
Ganache and I have experienced the game crashing while watching the replay attached. I suspect that the game runs out of memory saving all the rollbacks, we may want to limit the amount that we save to rewind.
[v046-2022-11-22-00-08-05-cawtellmeurname-L10-vs-yoschi-L10-Ranked-P1wins.txt](https://github.com/panel-attack/panel-attack/files/10070943/v046-2022-11-22-00-08-05-cawtellmeurname-L10-vs-yoschi-L10-Ranked-P1wins.txt)

**Comment by Endaris** [comment]
Resolved by panel-attack/panel-attack#757
