### ISSUE TITLE
it should not be possible to chain by swapping into a stack that is just about to fall.

### ISSUE THREAD

**Issue by jon12156** [panel-attack/panel-game#27]
Not sure how else to describe this, I may post a GIF later.

**Comment by sharpobject** [comment]
Add a replay please.

**Comment by jon12156** [comment]
[replay.txt](https://github.com/panel-attack/panel-attack/files/3078349/replay.txt)

green swap at about frame 608 (around 7 seconds in)
I don't think this type of chain is possible in PdP/TA.  Not sure if the swap should be disallowed, or whether it should just not be a chain somehow else.

**Comment by jon12156** [comment]
My bad, I've just been shown this is possible in TA.  Nevermind.
