### ISSUE TITLE
Character image data not being loaded properly or being unloaded

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#272]
There are various crash reports symptomatic for this.
The reason why character graphics are being unloaded are currently unknown.

The points of time for the crash are typically:

in graphics.lua:
`local portrait_w, portrait_h = characters[self.character].images[portrait_image]:getDimensions()`
typically in the middle of a game but has also been observed when returning to character select

in UpdatingImage.lua:
`assert(image ~= nil)`
at the end of a casual game

in graphics.lua:
`local corner_w, corner_h = imgs.topleft:getDimensions()`
while spectating

in graphics.lua:
`icon_width, icon_height = characters[self.character].images.face:getDimensions()`
typically upon starting to spectate a match

There might be other spots I've missed, I only checked those from the last month.
Our main source of crashes at the moment.
I tried to figure out why this happens based on reading the code various times with absolutely no results at all.

**Comment by JamesVanBoxtel** [comment]
I too can't understand why this happens. It super rarely happens to me, so I wonder if it has to do with specific characters or mods?

One thing we could do to help track it down is record in the error logs the current stage, theme, and character

**Comment by Endaris** [comment]
Also Stack.which while we're at it.

**Comment by JamesVanBoxtel** [comment]
{
  "detailedErrorLogString": "Stack Trace: \n\tgraphics.lua:956: in function 'render'\n\tmatch.lua:482: in function <match.lua:259>\n\tmain.lua:177: in function 'draw'\n\tCustomRun.lua:104: in function 'pa_runInternal'\n\tDefaultLoveRunFunctions.lua:55: in function <DefaultLoveRunFunctions.lua:53>\n\t[C]: in function 'xpcall'\nUsername: Zimtstern26\nTheme: Panel Attack Modern\nError Message: graphics.lua:826: attempt to index field 'face' (a nil value)\nEngine Version: 047\nBuild Version: 2023-03-08_05-28-30\nOperating System: OS: Linux\nLove Version: 11.4.0\nUTC Time: 2023-03-08 21:02:28\nvs Match Info: \n  Stage: pa_stages_king\n  Stacks: \n    P1: \n      Player Number: 1\n      Character: pa_characters_wiggler\n      Panels: pdp_ta_common\n      Rollback Count: 0\n      Rollback Frames Saved: 0\n    P2: \n      Player Number: 2\n      Character: pa_characters_hookbill\n      Panels: pdp_ta_common\n      Rollback Count: 0\n      Rollback Frames Saved: 0",
  "engine_version": "047",
  "stack": "\n\tgraphics.lua:956: in function 'render'\n\tmatch.lua:482: in function <match.lua:259>\n\tmain.lua:177: in function 'draw'\n\tCustomRun.lua:104: in function 'pa_runInternal'\n\tDefaultLoveRunFunctions.lua:55: in function <DefaultLoveRunFunctions.lua:53>\n\t[C]: in function 'xpcall'",
  "matchInfo": {
    "mode": "vs",
    "stage": "pa_stages_king",
    "stacks": [
      {
        "playerNumber": 1,
        "panels": "pdp_ta_common",
        "rollbackCopyCount": 0,
        "character": "pa_characters_wiggler",
        "rollbackCount": 0
      },
      {
        "playerNumber": 2,
        "panels": "pdp_ta_common",
        "rollbackCopyCount": 0,
        "character": "pa_characters_hookbill",
        "rollbackCount": 0
      }
    ]
  },
  "error": "graphics.lua:826: attempt to index field 'face' (a nil value)",
  "release_version": "2023-03-08_05-28-30",
  "theme": "Panel Attack Modern",
  "love_version": "11.4.0",
  "name": "Zimtstern26",
  "operating_system": "OS: Linux"
}

**Comment by JamesVanBoxtel** [comment]
It looks like it happens with standard characters... one speculation I had was a network message came in late after the game started and caused loading a different character? IDK if that's possible or not yet

**Comment by Endaris** [comment]
Should be impossible as we run on a single thread.
We don't pop `menu_state` messages anywhere except for select_screen and receiving the game start message leads us to return out of select_screen immediately.

**Comment by JamesVanBoxtel** [comment]
I think I may have discovered how this happens. The server starts the match when both players say they are ready. If one player changes their character after you are ready, then you might not have loaded it yet, but the server sends start match, so if you get the start match before loading their selection, you might crash.
