### ISSUE TITLE
Refactor panel state transitions

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#276]
This is currently one of the huge parts in `Stack.simulate` phase 2.
State transitions are rather confusing.
We should add documentation on what states can transform into which states and what timers they have.
It would be good if the `Panel` class itself contained this information (rather than the stack).
For easier/better behaviour division, it would be good to transform the current `panel.garbage` flag into a `panel.type` flag to differentiate more clearly and cleanly between empty panels, usable panels and garbage panels.
As far as possible, any references to solely graphics related functionality (such as popfx) should be moved to graphics - the panels should contain enough information for graphics (and maybe also sound) to determine the drawing without having access to extra engine information.
With the help of the state transformations it should also be possible to filter much more aggressively in `Stack.check_matches` which panels can actually match by only checking panels that just finished a transformation to a matchable state rather than all panels in a matchable state: it's to be assumed that most panels would be in "normal" state, thus matchable, thus getting checked but if their state didn't change, there is no way things could have changed from the previous frame where they should have already entered a matched state if they were part of a match.

**Comment by JamesVanBoxtel** [comment]
Yeah in general we should make all the panel and garbage objects more self contained. Having everyone accessing everything is all the more confusing and dangerous in lua.
