### ISSUE TITLE
Auto updater should fallback to the previous version if a downloaded version can't be mounted

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#296]
A downloaded version may turn out to be a faulty archive due to network-related issues.
Currently the auto_updater will give up if the file cannot be mounted and crash.
This causes the client to be caught in an eternal instant crash until either a newer version is uploaded on the server or the user manually deletes the corrupted file from its update folder.

If a .love file cannot be mounted, Panel Attack should delete said file and then scan the folder for other love files as it won't have deleted the previous version just yet.
If one is found, GAME_UPDATER:changeVersion needs to be called with the found version to revert the update to the faulty version. That way it is assured that the auto updater
1. won't delete that version on next startup
2. tries to download the new version again

Effectively guaranteeing that a working and somewhat recent client will startup regardless of network issues.

**Comment by JamesVanBoxtel** [comment]
This is now fixed.
