### ISSUE TITLE
Auto updater should handle download failures better

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#298]
If a download goes wrong, the auto_updater will change the local version to the newly downloaded one before trying to mount it.
If it can't mount it then, it just crashes with an error.
The previous version is usually not deleted until the next restart so here is what the auto_updater should do instead:

`setGameStartVersion` currently calls `GAME_UPDATER.change_version` on top of setting the local `gameStartVersion`.
The function should get removed and instead of calling it, all places in which it was called should get replaced with `gameStartVersion = version` directly.
In `start_game` it should be attempted to mount the `updaterDirectory..file,` directory.
If the new .love mounts successfully, that is a confirmation that the zip archive is sufficiently complete to unpack and therefore the download was successful. Call `GAME_UPDATER.change_version` in that case to confirm that the version has changed.
If the new .love can NOT be mounted, the auto_updater should try to mount `updaterDirectory .. GAME_UPDATER.local_version` which is the prior installed verson for the release stream (and the one already stored in the `.version` file).
On the next startup of the auto_updater, the auto_updater will automatically clean up any .love versions that do not match the version recorded in the `.version` file via `cleanUpOldVersions`, causing the failed download file to get cleaned up as well, causing the auto_updater to try its luck anew with downloading the new version.

**Comment by JamesVanBoxtel** [comment]
I'll try not to upload straigh into the download folder on the server and just move after its uploaded. That should avoid this issue mostly, though not fully.

That would probably be enough to make this a low priority issue?

**Comment by Endaris** [comment]
Honestly that Musichael thing was such an insane edge case. Especially because your upstream isn't slow at all, I'd reckon you take like anywhere between half a second and maybe 5 to upload our ~10MB love file?

It's much more likely that someone like me with internet that is like 150-300kB/s down on average while somewhat frequently experiencing brief cuts will get their download interrupted and then they have effectively a bricked install until the next version is on the server. 

I'm not entirely sure how it worked with the old auto_updater but I had the impression that on many occasions it wouldn't even DL the new version inside the auto_updater main and it would get downloaded by the GAME_UPDATER passed to the maingame instead. Remember how we always had this phenomen of starting the game, then waiting a couple seconds and then getting the "A new version is available, restart now!"  thing a lot of times when new versions where published?

With the changes done I think it is now standard for the auto_updater to always fully download inside of its own main making this problem occur much more likely to appear in reality.
Since most users will require help with unbricking their installation I don't think we should label this low priority.

**Comment by JamesVanBoxtel** [comment]
Hmm I guess your right. I'm okay leaving or increasing the priority then. I'll let you take the lead on this one since you know that code the best.

**Comment by Endaris** [comment]
I'm gonna dare say with the way I wrote the issue, even Buster might be able to implement this. Let's see if he reads this and takes me up on it, LOL.
Fixing this tomorrow.
