### ISSUE TITLE
Serious framedrops when playing a replay for a long amount of time

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#299]
Early on:
![grafik](https://cdn.discordapp.com/attachments/362093490538020864/1065122699778732152/image.png)

Late:
![grafik](https://cdn.discordapp.com/attachments/362093490538020864/1065124032942460949/image.png)

(Both screenshots taken at 1x playback speed, the brickwall on the right side in the first screenshot can be attributed to my screenshot tool hogging the CPU or something like that)
This type of behaviour does not show in online spectate and is thus restricted to replays.
There is very likely something going wrong with rollback, causing us to rollbackCopy increasing amounts of information with every passing frame, causing the crazy increase in memory usage and frametimes.
Based on a comparison between the memory and frametime bars, I strongly suspect that aside from our way of doing rollacks being crap in some way. Either something is wrong with our cleanup too or there's just so much crap to be garbage collected that the game just goes wild at that point.

**Comment by JamesVanBoxtel** [comment]
Yes likely garbage collection is to blame here.

we need to look into whats getting stored and how we can store it more efficently
4 seconds * 60 frames * all the crap thats stored from game start * a 10 minute game
that can really add up

one quick idea I have. Some of the variables store things that happen on specific frames. Like combos and chains etc.

Anything with that kind of data structure should be stored in one single table and when we rollback we delete everything from the rollback frame on in that table.

That would save a ton of garbage generation.

**Comment by Endaris** [comment]
I tested a version where I told the game to use half of its planned sleep time for garbage collection instead.
The result:
![grafik](https://user-images.githubusercontent.com/22120694/214213117-f656a08a-8c3c-43e0-82c4-24a01b454691.png)
Until about 9min in, garbage collection could keep up just fine.
After that, due to the configured 64MB Lua memory limit in the manual GC, the game keeps defaulting to `collect` in place of `step` - even though the vast majority of memory is obviously not up for collection.

What is interesting though is the following:
Before reaching that bottleneck owed to manual gc configuration, the game still generates massive spikes and it does not attribute them to the GC but instead to update + draw:
![grafik](https://user-images.githubusercontent.com/22120694/214213494-dd193574-747a-498d-9dd2-95d8b1c2eb6b.png)

Another very weird thing is that this behaviour continues even while the game is paused which should keep the biggest part of `update` from running. But it still accumulates visible spikes.

**Comment by JamesVanBoxtel** [comment]
We definitely should up the memory limit. We also should definitely collect garbage for up to the whole sleep time. I believe it will stop early if there's no work to be done.

Finally we probably need to implement the fixes to engine to not accumulate extra memory. I probably should be in charge of that part since I know it the best
