### ISSUE TITLE
Save CPU time outside of games

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#307]
The current beta eats a lot into CPU by spending a lot of time actively collecting garbage during `CustomRun.sleep`.
There is no real point to this outside of gameplay/replays.
It probably makes sense to only actively collect garbage if lua memory exceeds a certain limit as menus typically require very little lua memory.

**Comment by JamesVanBoxtel** [comment]
Or only collect extra garbage when in an actual game
