### ISSUE TITLE
Modern theme can't be modified under the same name

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#310]
Reported by Lava

Repro
1. Empty your theme folder and start PA so the default theme gets copied in as `__Panel Attack Modern`
2. Enable the folder for loading by renaming it to `Panel Attack Modern`
3. Switch out `background/main` for something else and restart the game
-> The game does load the image from the .love instead of the theme folder.

Imo it should be possible to edit and overwrite standard theme assets.
It is confusing to say the least if there is a theme folder that the game ignores without telling you.

**Comment by JamesVanBoxtel** [comment]
Tested this out and it's not reproducing for me. My overrides are working

**Comment by Endaris** [comment]
No longer considered an issue, see #362
