### ISSUE TITLE
Crash selecting stage

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#319]
{
  "detailedErrorLogString": "Stack Trace: \tselect_screen/select_screen.lua: in function 'change_stage'\n\tselect_screen/select_screen.lua:621: in function 'handleInput'\n\tselect_screen/select_screen.lua:1009: in function 'f'\n\tmainloop.lua:115: in function 'variable_step'\n\tselect_screen/select_screen.lua:999: in function 'func'\nUsername: Mexico\nTheme: Planet Puzzle League\nError Message: main.lua:145: select_screen/select_screen.lua:264: attempt to perform arithmetic on local 'currentId' (a nil value)\nEngine Version: 047\nBuild Version: 2023-03-07_05-28-43\nOperating System: OS: Windows\nLove Version: 11.4.0\nUTC Time: 2023-03-08 00:40:43",
  "engine_version": "047",
  "stack": "\tselect_screen/select_screen.lua: in function 'change_stage'\n\tselect_screen/select_screen.lua:621: in function 'handleInput'\n\tselect_screen/select_screen.lua:1009: in function 'f'\n\tmainloop.lua:115: in function 'variable_step'\n\tselect_screen/select_screen.lua:999: in function 'func'",
  "error": "main.lua:145: select_screen/select_screen.lua:264: attempt to perform arithmetic on local 'currentId' (a nil value)",
  "release_version": "2023-03-07_05-28-43",
  "theme": "Planet Puzzle League",
  "love_version": "11.4.0",
  "name": "Mexico",
  "operating_system": "OS: Windows"
}

**Comment by JamesVanBoxtel** [comment]
Endaris this looks like if the stage doesn't resolve we might get a nil index and we should protect against that?

**Comment by Endaris** [comment]
That code only gets called if the client side player changes the selection.
That's also the first time this occurs in spite of the relevant code not being changed in a very long time.
Effectively this error says that the player picked a stage they don't have which should be all means be impossible.
I'll put this on wontfix until someone reports this again.

**Comment by JamesVanBoxtel** [comment]
fair enough, I just went through all the server crash logs and this was the only other one not already documented I think
