### ISSUE TITLE
opponentStack on the stack class should be abstracted away

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#322]
It is doing too many things and the stacks are interconnecting with each other's variables.

The match object should probably handle all interactions and do so in a way that handles many game modes including more than one opponent

**Comment by Endaris** [comment]
They're still loosely coupled via `garbageTarget` which will be unavoidable in the short term and besides graphics it is only treated as a garbageTarget rather than a stack.
`opponentStack` is history now.
