### ISSUE TITLE
Training mode garbage should not send fake chains

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#325]
We should remove the hack in Stack.shouldDropGarbage when we fix this

**Comment by Endaris** [comment]
Labelled as a bug because it being combo garbage makes it possible to hold it back, causing divergence in behaviour from normal chain garbage which has to be considered a bug.

**Comment by AegisCrusader** [comment]
I don't think I agree with labeling as a bug since it was technically intended to work this way to start, we just wanna change it now.

**Comment by Endaris** [comment]
This has been (inadvertently) fixed with the garbage queue rework leading up to v048.
