### ISSUE TITLE
Garbage blocks sometimes overlap one another

### ISSUE THREAD

**Issue by Raspberryfloof** [panel-attack/panel-game#33]
I don't have a replay file of this happening on the latest build, but several were posted on Discord a few weeks ago on older builds.

**Comment by JamesVanBoxtel** [comment]
Does this still happen?

**Comment by Raspberryfloof** [comment]
I believe I fixed this a very long time ago, or at least tried to. (in https://github.com/panel-attack/panel-attack/commit/27980b890c941b83dd72691d1197e8b466b1c198 and the subsequent few commits)  I haven't heard of any reports of it happening since then.
