### ISSUE TITLE
Last pop on garbage should make a sound and make popFX

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#330]
There is a bug in current stable / beta that the last pop of garbage panels does not generate a sound or popFX

Classic versions of these style games do make the noise and pop fx.

**Comment by chickenwaffle** [comment]
Can confirm.  Looking into it now.

https://github.com/panel-attack/panel-attack/assets/7853187/5a9eb55e-3fc3-40b2-bca9-4ddc51fb3f82

**Comment by Endaris** [comment]
Fixed with dcc9cf677fba1ffe5037f3abe9ff7f993321861b
