### ISSUE TITLE
Need combo cards 67-72 for Panel Attack Modern theme

### ISSUE THREAD

**Issue by chickenwaffle** [panel-attack/panel-game#334]
There are no combo card images higher than 66 in the modern theme.  The +72 in the 2nd level in Ridiculous Mode breaks the game because there is no combo card image for a combo that high.

https://github.com/panel-attack/panel-game/assets/7853187/32098f17-178c-41da-ade3-bd779ce36986

**Comment by JamesVanBoxtel** [comment]
Definitely should make sure we get a unit test for this and chains. Should be a simple fix if anyone wants to take the lead
