### ISSUE TITLE
add vsync on/off option / FPS is capped at monitor refresh rate

### ISSUE THREAD

**Issue by Raspberryfloof** [panel-attack/panel-game#34]
For at least Intel graphics drivers, FPS is capped at the monitors' refresh rate.  By default, this is 40Hz, so FPS is capped at 40.

A workaround currently is to change your monitors' refresh rate to 60Hz (if supported).

**Comment by jon12156** [comment]
I changed the title here.  hmm. I haven't seen the webhook for our discord announce changes recently.  Checking if this shows up in #github...

**Comment by JamesVanBoxtel** [comment]
We have a vsync option now. This is done right?
