### ISSUE TITLE
Inputs sometimes drop when using a controller

### ISSUE THREAD

**Issue by Raspberryfloof** [panel-attack/panel-game#35]
Per sharpobject, we use polling for controller input instead of events, which could cause dropped inputs (since we might not capture every controller input event).  There might not be an API for this within Love yet?  Needs more research...

**Comment by jon12156** [comment]
this is especially noticeable when the game isn't running at quite 60fps

**Comment by JamesVanBoxtel** [comment]
To be a little more verbose, the game logic runs in  the variable_step function, which is expected to run fast, 60 times per second.

If it runs slower than that, then you may have released the key before it registered it, and so it gets ignored.

We need to keep a queue of your inputs, but still handle the input repeat functionality. That way, worse case, the input repeat is lost or slow, but normal key presses are not lost.

**Comment by JamesVanBoxtel** [comment]
After researching this more there are two problems going on here.

1. Making sure we get events for each button press. This is true for everything but joystick events which we can't do anything about.

2. Dealing with when variable_step runs many times in a row. When this happens all the later frames can't have input. The only reasonable way to deal with this is to increase performance so this doesn't happen.

I think given that we can close this and just write up bugs for performance issues we observer.

**Comment by Endaris** [comment]
panel-attack/panel-game#461 covers the part regarding joystick events
I think the remainder of the issue is not actionable as mentioned by Jam
