### ISSUE TITLE
Make shake animation less disruptive

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#376]
Some people easily lose their cursors due to the pretty big displacement of an entire row with max shake.
There should be a way to reduce the displacement while keeping the perceived impact of shake.

There is currently a poll going on in [#surveys](https://discord.com/channels/196674532491132937/375498107137556490/1167503987801591929).
Up to debate is:
Should this be a change to the standard or an option?
I think standard, to avoid options bloat.
Some think no option because it impacts the competitive baseline as playing with less shake is arguably easier.
An option would satisfy those that would like less shake and those that would like to keep the same shake while dissatisfying the no-option advocators.

**Comment by JamesVanBoxtel** [comment]
Note we have less than 80% agreement that this should happen even with an option.

Without an option I think people are going to be even more opposed to this, but if you want to put that into a new survey on the discord and champion it I'm okay with that.

I've been playing at half animation for about a week and it seems just right.

**Comment by AegisCrusader** [comment]
I agree that there should be an option, but I don't want it to be a forced change. Maybe it could even be a number that controls the magnitude.

**Comment by Endaris** [comment]
Closed panel-attack/panel-attack#1176 , I'll do another survey around start of 2025 to check reception if further shake reduction is truly necessary
