### ISSUE TITLE
Hitting two opposite directions on a joypad's analog stick or d-pad crashes the game.

### ISSUE THREAD

**Issue by XKirby** [panel-attack/panel-game#40]
I know this shouldn't be possible in the first place, but my Logitech F310 has a really loose D-Pad and I can push the entire thing in, pressing both left and right at the same time. If I do this, the game crashes.

![image](https://user-images.githubusercontent.com/34034109/65534551-af2af200-decd-11e9-875e-061be1cee6aa.png)

**Comment by ghost** [comment]
```LUA
Error

main.lua:61: input.lua:56: attempt to concatenate a nil value
stack traceback:
input.lua: in function 'hat_to_button'
input.lua:84: in function 'joystick_ax'
mainloop.lua:114: in function 'variable_step'
mainloop.lua:1787: in function 'func'
mainloop.lua:104: in function mainloop.lua:29

Traceback

[C]: in function 'error'
main.lua:61: in function 'update'
[C]: in function 'xpcall'
```

when i'm moving in game and press every directions at the same time:
1 - on linux inputs aren't registered correctly and lock the inputs. i can't move anymore until i get a neutral position on the d-pad (nothing pressed)
2 - on windows the game completely crash with the error above

doesn't seems to happend on keyboard

**Comment by JamesVanBoxtel** [comment]
Does this still happen?

**Comment by Endaris** [comment]
Afaik some gamepad input crashes were fixed in the past and we didn't have any in a really long time.
Please open a new issue if you encouner problems with your controller.
