### ISSUE TITLE
Options menu entries aren't properly aligned

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#403]
Things are basically not aligned properly.
This is (in my opinion) owed to each menu entry only being a pseudo-cohesive whole but really just 2 completely separate item that `Menu` happens to assign the same `y`.
The easiest solution to make sure everything is center aligned is to actually add both items to a parent items, have the left element use `hAlign = "right"` and offset its `x` to `- parent.width / 2` and respectively the right element use `hAlign = "left"` and offset its `x` to `parent.width / 2`. The width of the parent can really be anything but should be screen centered so really `consts.CANVAS_WIDTH` would work just fine or alternatively just `hFill = true` with the `Menu` parent being wide enough to accomodate all options.

**Comment by JamesVanBoxtel** [comment]
I believe with my current refactors these are generally centered now and good enough. Can polish more when we prettify or redo options to a final design
