### ISSUE TITLE
Make theme switching performant

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#405]
Themes should have the option to load up for a preview, akin to how characters only have their icon and selection sfx loaded before being selected.
When switching the theme in options, only these preview assets should get loaded and saved in a table local to the options menu for quick flickarounds between themes. If restricting to these basic assets it should be fine to lazy load themes as they're being scrolled through.
Relevant assets are:
- theme font
- main menu background
- main menu music
- about menu background
- menu_validate
- menu_move
- menu_cancel

One thing to look out for is that the theme font should only be set if there is no language specific font loaded. Not sure how this is currently handled otherwise?

**Comment by JamesVanBoxtel** [comment]
IDK if we should really block scene refactor on this. Seems only like a nice to have.

**Comment by Endaris** [comment]
If someone has a bunch of themes, we might hog several 100 MB of memory upon flipping through themes, lasting until restart because they're never getting released.
While we don't have to do the "cool" way I suggested here, I think we should at least release the hogged memory upon leaving options and we should check if a theme is already loaded before we switch (because currently it is getting reloaded, even if it already is loaded).

**Comment by Endaris** [comment]
Implemented with [f87aa52](https://github.com/panel-attack/panel-attack/commit/f87aa529a9b4d2c0b3684654ed228222ec47c8e1)
