### ISSUE TITLE
SceneRefactor: Crash closing game

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#414]
Error

Stack Trace: 
    [C]: in function 'onClick'
    ui/Button.lua:39: in function 'onRelease'
    ui/touchHandler.lua:40: in function 'release'
    main.lua:127: in function <main.lua:125>
    CustomRun.lua:81: in function 'processEvents'
    CustomRun.lua:91: in function 'pa_runInternal'
    CustomRun.lua:178: in function <CustomRun.lua:176>
    [C]: in function 'xpcall'
Username: JamBox2x
Theme: Panel Attack Custom
Error Message: ui/Button.lua:39: Cycle detected in table
Engine Version: 047
Build Version: Unknown
Operating System: OS: OS X
Love Version: 11.5.0
UTC Time: 2024-01-14 02:30:55Scene: MainMenu

**Comment by Endaris** [comment]
What is the repro for this?

**Comment by JamesVanBoxtel** [comment]
Huh I can't repro now, guess I'll close unless we see it again
