### ISSUE TITLE
Spectate occasionally bricks

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#416]
Occasionally while spectating, the room reaches a state where a match is started and quickly ends with nonsensical inputs on the side of both players, staying on the match end screen until the next match_start message arrives.
This then goes on until rejoining the room.
Not confirmed what the cause is yet although I suspect leftover messages from an old match could play into that.

**Comment by Endaris** [comment]
Occured to me 1 or 2 times while spectating this set:
http://panelattack.com/replays/v047/2024/01/16/Sankyr-vs-ZaUa/
These are my local replay files for comparison
[Sankyr-vs-ZaUa.zip](https://github.com/panel-attack/panel-attack/files/13951438/Sankyr-vs-ZaUa.zip)
When I find time, I'll try to find a more clinical set where I can specifically name where it bricked and when I quit and rejoin spectate.

**Comment by JamesVanBoxtel** [comment]
This definitely sounds like the bug where inputs from the previous game go to the next game. Because the game can game-over before all messages come through you need to make sure to track the order of the next game start message and remove all inputs that came in before that.
