### ISSUE TITLE
SceneRefactor: Puzzle Fixes

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#433]
- [ ] During puzzles you don't fail on chain puzzles
- [ ] should also test clear puzzles
- [ ] test move puzzles
- [ ] Also can't reset without crashing

**Comment by Endaris** [comment]
Couldn't reproduce most of these, likely due to earlier changes I don't remember right now.
Remaining puzzle issues should be fixed with https://github.com/Endaris/panel-attack/commit/1fadbdb4033f9c98eefc1a778e4a9b7a4b3e3a34
