### ISSUE TITLE
Engine: Raising should be cancelled if stack height increases

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#436]
If you started raising before garbage dropped shouldn't keep raising after garbage landed and shake depleted.

Instead pressing raise should only do something if raising is currently allowed, and once it starts it should cancel whenever rise hits the next row, garbage lands or a match happens.

**Comment by z26** [comment]
Havent done a fix yet, but I at least came up with a plausible explanation here https://discord.com/channels/196674532491132937/559122941216817164/1201985793900675112

**Comment by Endaris** [comment]
Implemented in #552
