### ISSUE TITLE
SceneRefactor: Joining an online match that is in progress regularly fails

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#438]
As long as the match is about 10 seconds in or so it seems to fail.

Seems like this broke in the last week or so.

**Comment by JamesVanBoxtel** [comment]
This sometimes happens and sometimes doesn't, haven't tracked down why yet.

**Comment by Endaris** [comment]
Still haven't been able to reproduce this, will reopen if someone encounters this during canary testing.
