### ISSUE TITLE
Lobby is missing the messages at top

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#447]
"select a player name" etc 

and

~~"Join the community at"~~ fixed since
<img width="434" alt="Screenshot 2024-02-04 at 8 31 42 AM" src="https://github.com/panel-attack/panel-game/assets/8935453/17b24792-8234-4616-8c84-e681508c9107">

**Comment by Endaris** [comment]
Label is there now, bad thing is that you can actually navigate it as part of the menu but that's for another day
[3c9c35d](https://github.com/panel-attack/panel-attack/commit/3c9c35d30ecfffaa04e6540abb8ff815501316fe)
