### ISSUE TITLE
SceneRefactor: Menu Sound Effects Work

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#449]
- [x] On escaping out of an options submenu, the validate sfx plays instead of the cancel sfx
- [x] On exiting a readme, cancel and validate sfx play simultaneously.
- [x] The difficulty selector for challenge mode does not play sfx on changing the selection, nor does the start button in the same menu.
- [x] Upon clicking the "Options" button in the main menu, more than the usual amount of SFX seems to play.

**Comment by Endaris** [comment]
Fixed
