### ISSUE TITLE
Feature: Playfield background darkness

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#45]
The default character backgrounds are bright, as are most modded-in characters. But the actual PDP games darken the backgrounds once play begins. I'd like to request a feature that automatically darkens the playfield backgrounds, which could be just as simple as overlaying a translucent black box in front of the background and behind the panels. Maybe give it a percentage option in the settings (0% would be the way it is now, 100% would make the background pitch black regardless of character).

**Comment by MizunoKetsuban** [comment]
It might help if I provide a visual demonstration. 
On the left is how backgrounds currently look in Panel Attack, and on the right is how the backgrounds are processed in actual PDP games.
![image](https://user-images.githubusercontent.com/80512906/115104609-424bd280-9f1f-11eb-9a92-28d56d3aaac6.png)

**Comment by JamesVanBoxtel** [comment]
This feature is implemented now so I think we can close this?
