### ISSUE TITLE
Wrapping with controller

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#450]
Menu navigation does not wrap around to select the last index when going up from the first index (mostly an issue when you have a lot of puzzles in puzzle menu).

JamBox made this change on purpose so it was easier to hold up to go to the top, but maybe it's not worth changing? Needs research on what most games do.

**Comment by Endaris** [comment]
Implemented with [a83cb99](https://github.com/panel-attack/panel-attack/commit/a83cb9978fdb9691bd8f4972642576c6731e33a8)
We could revert this very easily but for now I'm going with how it previously worked.
Can be revisited when the game's menu structure is being reworked.
