### ISSUE TITLE
Custom Puzzles v2

### ISSUE THREAD

**Issue by Endaris** [panel-attack/panel-game#46]
Right now, puzzles come with several downsides:

- There is no navigation within collections.
- Puzzles can't be replayed without going through the whole collection again.
- There is no way to identify a specific puzzle in a collection.
- There is no way to represent actual garbage.
- The requirement of the field being cleared of blocks to get a solved puzzle limits the use-cases for creating puzzle (e.g. making a puzzle collection to practice shoguns)

Idea: Create a downwards-compatible new specification to make puzzles more practical, flexible and useful, in short, make it possible to emulate every situation you may find yourself in in vs gameplay.

To do this, I suggest allowing the addition of 3 more fields to each custom puzzle:
["numbers mapping out puzzle 1 in this set", Number of moves allowed, "name of the puzzle", "solution boardstate", "level"]

To make sure that old puzzles work as expected, following default values can be used in case they aren't found in a puzzle.txt

name of the puzzle: A name that describes this puzzle. Shown when navigating a puzzle set. 
default: 1-based index of the puzzle in the set

solution boardstate: numbers mapping out the puzzle when solved
default: Only panel colors 0 and 9 on the board

level: which vs level should be used for the game physics (minus stack raising of course)
default: whatever game physics are being used for puzzles right now

Furthermore it would be *great* to have functional garbage in puzzles for more advanced shogun puzzles, because color 9 garbage is considered as a normal panel and won't fall just because an adjacent panel to either side fell.
This would come with an extension of the possible "panel colors" to be used in puzzles.

Following idea for encoding that:
\# = panel of any color (0-9), used to represent cleared garbage falling down and panels that might have got cleared as a result of falling panels
[ = left side (end) of garbage
] = right side (start) of garbage
= = garbage body
{ = left side (end) of shock garbage
} = right side (start) of shock garbage
~ = shock garbage body

Example (with rows to make it more readable):
```
{
"Shogun practice":
[
["
929999  //shogun example, works in current version
999999
040000
224999
949999", 1], //solution: 909999909999000000000999999999
["
929999
[====]
040000
224999
949999", 1, "Shogun example in new specification", 
"000999
909999
909999
999999", 5],
["456412
  [====]
  000013
  000035
  000032
  020066
  262015
  145534", 2, "Simple Shogun Setup 1", 
 "000002
  00000#
  0#0001
  ###0#5 //the green, red and yellow panels might match with the cleared garbage, so they're marked as #
  ###0#2 //the purple panel on top would fall down so it is marked with # too
  262##5
  145534", 5],
]
}
```

With custom puzzles v2, clicking on a puzzle collection wouldn't immediately start the first puzzle but instead show another subnavigation with a "Play from start" option (that would do what currently happens) and the puzzle names listed for selection.

I have no idea how hard all of this would be and it is likely possible and desirable to split this into multiple issues but I wanted to share my thoughts and discuss this to see if there are any drawbacks.
I'd be up to try my hands on actually putting it into the game (although I haven't worked with lua yet) if the ideas are considered good and feasible.

**Comment by Endaris** [comment]
Instead of doing the placeholders (which is quite complicated to work out) the gpanel_buffer could be flushed with panels of color 9 to make sure they drop into something that cannot possibly generate further matches.
Would make the creation of the "solved" state much easier.

For the above example the solution boardstate would then be 
000002
000009
050001
494015
929092
262915
145534

**Comment by JamesVanBoxtel** [comment]
There are some great ideas here. In addition I think we should expand the possiblities for win conditions. like "get a 10 combo" or "get a 4x chain"

**Comment by MizunoKetsuban** [comment]
If you want ideas for additional win conditions, I suggest looking into the Mission mode of Planet Puzzle League.

**Comment by Endaris** [comment]
Personally I don't like the thought of doing everything at once. In my opinion a good puzzle - even an explorative one - should be designed in a way that there is one best solution.
To address the win conditions in a roundabout way without being forced to implement them right away along with puzzles v2, the proposed puzzle spec could be changed to
```
["numbers mapping out puzzle 1 in this set", //required
 Number of moves allowed, //required
 "name of the puzzle", //default: 1-based index of the puzzle in the set
 "level",                    // default 5
 win condition type, //default 0
 "win condition"] //default empty
```

where `win condition type` is an enum that makes PA read the value in the win condition field differently:

Win condition types:
0 - clear board state, win condition is all 0s or 9s
1 - solution boardstate, win condition is getting compared to the board state after no moves are left

And later you could add something like
2 - garbage result, win condition is the garbage in the queue
^ not sure if comparing garbage or actual chains is easier but personally I imagine checking the garbage queue should technically be easier because chains and combos are fleeting things that probably are harder to track than the garbage that goes into the queue (which should be there, just with no target stack although I'm not sure how that gets handled internally then)

Not sure what else you might come up with later on but it would certainly give room to add more win conditions later on.

I checked a YT vid where someone did planet pl missions and I have to say, I don't like it. Without the move-restriction, you can just derp so hard, it does not really hold a value for practicing efficient movement or anything like that.
I feel like you could make a good puzzle with move restriction for every mission I've seen (first mission set is the only one I was able to find to be fair) but there were many I just found kinda worthless or uninteresting without a move restriction.
These still could be done later on, you'd only have to make PA check the win condition after every move and set the move restriction very high so it's virtually the same but personally I think they hold relatively low value compared to the puzzles that get enabled with puzzles v2 as suggested so far.

**Comment by Endaris** [comment]
Further ideas...
From JamBox:
Puzzles should come with an attached replay solution. There could be another property for hints.

From me:
To create good garbage clear puzzles, garbage tiles could be numbered inside the bracket so that a win condition could be "clear garbage panel-attack/panel-attack#2"

**Comment by AegisCrusader** [comment]
Closing because of panel-attack/panel-attack#491
