### ISSUE TITLE
Dynamic music setting

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#47]
An option for stages and characters to have the music "swap" instead of "replace". What I mean is that instead of the music starting from the beginning every time the threshold is crossed, both technically play simultaneously, with one being silenced until it's called for, in which case the tracks then "swap". It could be used for tracks that simply want to add a warning siren (like PLDS) or play an alternative version of the normal music (like ACPL) when the stack is in danger. 
https://www.youtube.com/watch?v=GrnxJiZMYB8 
https://www.youtube.com/watch?v=xqqtQ0bvoHI

**Comment by MizunoKetsuban** [comment]
Attached below are two examples of this dynamic music feature (demonstrated through video editing).

https://user-images.githubusercontent.com/80512906/121322734-d9585980-c8d4-11eb-81e0-1db83a22036c.mp4

https://user-images.githubusercontent.com/80512906/121322753-deb5a400-c8d4-11eb-9d6e-cd56f67f0e9d.mp4

**Comment by JamesVanBoxtel** [comment]
If we can get music files as awesome as these, this feature would be killer.

**Comment by JamesVanBoxtel** [comment]
This is now implemented in alpha.
