### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#53]
The codebase has evolved quite a bit and has quite a bit of technical debt that has built up over the years.

Here is a list of things I think could be useful to do to without changing any functionality to make things easier for the future. Feel free to add more suggestions or comment on which you think are bad or good ideas.

- [ ] Improve Documentation
- [x] - 	simple comment before each function
- [ ] - 	general documentation of the code structure
- [ ] - 	how to make builds
- [ ] - 	update server protocol docs
- [ ] 
- [ ] Reduce scope of variables
- [ ] Reduce size of functions
- [ ] Reduce Globals
- [ ] - Use ALL_CAPS when a global is still needed
- [ ] Separate functionality into classes with packages
- [x] Reduce code duplication
- [x] Delete unused code / comments
- [ ] Organize into folders

**Comment by AegisCrusader** [comment]
Me and James believe that we should not implement any more features yet other than the pull requests that currently exist until this is finished.

**Comment by AegisCrusader** [comment]
I have re-formatted the files to be in compliance with lua standards

**Comment by JamesVanBoxtel** [comment]
Some of this work is done, lets keep doing the rest as we go

**Comment by Endaris** [comment]
This issue is way too broad and can never ever be finished as it is now.
While there is still cleanup work to be done, it should be addressed in concrete issues that names specific code segments that need to be improved.
I'll open separate issues for the checkboxes that can be viewed as concrete work items.

**Comment by JamesVanBoxtel** [comment]
Agreed, we can track specific things, and we have already updated the readme to encourage these principles.
