### ISSUE TITLE
Players get thrown out of matches after spectating, then completing a game.

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#55]
- two players join the server and spectate the same match
- these two players then decide to stop spectating and play vs each other
- they will have the same rating points as the players they just spectated
- after the first match of them finishes everyone gets thrown out of their matches/lobbies
- can be circumvented by going back to menu before starting the match that would cause the crash 

Happens in all builds

**Comment by JamesVanBoxtel** [comment]
What we know so far:

The room numbers are getting completely changed for everyone in a game. In this screenshot I believe the JamesTest game used to have a room number of 1805, but now its 1809

<img width="640" alt="2021-11-01 at 22 46 16@2x" src="https://user-images.githubusercontent.com/8935453/139792961-97924587-5194-43ea-a67d-6e48c6e4e436.png">
.

**Comment by AegisCrusader** [comment]
Yes, I confirmed this through testing. I also discovered that the room number can sometimes overwrite another room number, giving duplicates.
