### ISSUE TITLE
game crashes in endless mode

### ISSUE THREAD

**Issue by fsbr** [panel-attack/panel-game#569]
I just started the game fresh.  
I'm on linux

steps to reproduce:
1.  I ran the game using the love.appImage
2. Open 1P endless mode
3. lose the game by filling the screen to the top.

Error: Please share your crash.log with the developers to get help with this!

client/src/scores.lua:73: attempt to compare number with nil

here is the relevant code:

function Scores.saveEndlessScoreForLevel(self, score, level)
  self.endless[level]["last"] = score
  if self.endless[level]["record"] < score then  -- the problem is here.
    self.endless[level]["record"] = score
  end
  self:saveToFile()
end

do i need to take extra steps to initialize the key value pair on "level" and "record"? Idk much about lua this is my first time looking at.

**Comment by fsbr** [comment]
crash.log

12/27/24 10:59:48.337 DEBUG:No file at specified path scores.json
12/27/24 10:59:48.366 DEBUG:loading custom puzzles...
12/27/24 10:59:48.366 DEBUG:loading custom puzzle set: stock (example).json
12/27/24 10:59:48.368 DEBUG:loaded above set
12/27/24 10:59:48.368 DEBUG:Launching game without updater
12/27/24 10:59:48.369 DEBUG:Pushing scene StartUp on top of stack
12/27/24 10:59:48.370  INFO:Connecting new device 1411;8288;272;USB,2-axis 8-button gamepad;0300dafe830500006020000010010000;1
12/27/24 10:59:48.370  INFO:Connecting new gamepad 0300dafe830500006020000010010000,iBuffalo SNES Controller,a:b0,b:b1,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,rightshoulder:b5,start:b7,x:b2,y:b3,hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,platform:Linux,
12/27/24 10:59:48.370  INFO:Gamepad has 2 axes
12/27/24 10:59:48.413 DEBUG:loading theme Panel Attack Modern
12/27/24 10:59:48.833 DEBUG:preloading stage __default
12/27/24 10:59:48.853 DEBUG:loaded stage __default
12/27/24 10:59:48.853 DEBUG:loaded theme Panel Attack Modern
12/27/24 10:59:48.856 DEBUG:panel-attack-magellan-day has been added to the stage list!
12/27/24 10:59:48.856 DEBUG:panel-attack-magellan-night has been added to the stage list!
12/27/24 10:59:48.856 DEBUG:preloading stage __default
12/27/24 10:59:48.877 DEBUG:loaded stage __default
12/27/24 10:59:48.877 DEBUG:preloading stage panel-attack-magellan-day
12/27/24 10:59:48.878 DEBUG:preloading stage panel-attack-magellan-night
12/27/24 10:59:48.880 DEBUG:loading panels Panel Attack
12/27/24 10:59:48.894 DEBUG:loading panels pacci
12/27/24 10:59:48.918 DEBUG:No file at specified path client/assets/default_data/characters/Esme/telegraph/config.json
12/27/24 10:59:48.920 DEBUG:No file at specified path client/assets/default_data/characters/Magellan/telegraph/config.json
12/27/24 10:59:48.921 DEBUG:PA_Magellan has been added to the character list!
12/27/24 10:59:48.921 DEBUG:PA_Esme has been added to the character list!
12/27/24 10:59:48.943 DEBUG:loaded character __default
12/27/24 10:59:49.019 DEBUG:Loading character PA_Esme as part of refreshCharacter for player brocolli
12/27/24 10:59:49.019 DEBUG:Registering mod PA_Esme
12/27/24 10:59:49.019 DEBUG:Adding mod PA_Esme to unload list
12/27/24 10:59:49.019 DEBUG:Queueing mod PA_Esme, fullyLoaded: false
12/27/24 10:59:49.019 DEBUG:Loading stage panel-attack-magellan-night as part of refreshStage for player brocolli
12/27/24 10:59:49.019 DEBUG:Registering mod panel-attack-magellan-night
12/27/24 10:59:49.019 DEBUG:Adding mod panel-attack-magellan-night to unload list
12/27/24 10:59:49.019 DEBUG:Queueing mod panel-attack-magellan-night, fullyLoaded: false
12/27/24 10:59:49.025 DEBUG:Replacing scene StartUp with scene TitleScreen
12/27/24 10:59:49.651 DEBUG:Replacing scene TitleScreen with scene MainMenu
12/27/24 10:59:51.419 DEBUG:Pushing scene EndlessMenu on top of stack
12/27/24 10:59:51.428 DEBUG:Preparing to load mod PA_Esme
12/27/24 10:59:51.428 DEBUG:Loading mod PA_Esme
12/27/24 10:59:52.684 DEBUG:loaded character PA_Esme
12/27/24 10:59:52.700 DEBUG:finished loading mod PA_Esme
12/27/24 10:59:52.700 DEBUG:Loading stage panel-attack-magellan-night as part of BattleRoom:startLoadingNewAssets
12/27/24 10:59:52.717 DEBUG:Preparing to load mod panel-attack-magellan-night
12/27/24 10:59:52.717 DEBUG:Loading mod panel-attack-magellan-night
12/27/24 10:59:52.934 DEBUG:loaded stage panel-attack-magellan-night
12/27/24 10:59:52.956 DEBUG:finished loading mod panel-attack-magellan-night
12/27/24 10:59:56.603 DEBUG:Claiming input configuration 1 for player 1
12/27/24 10:59:56.620 DEBUG:Setting match stage id to 
12/27/24 10:59:56.620 DEBUG:Registering mod panel-attack-magellan-night
12/27/24 10:59:56.620 DEBUG:Queueing mod panel-attack-magellan-night, fullyLoaded: true
12/27/24 10:59:56.692 DEBUG:Force loading character PA_Esme as part of GameBase:load
12/27/24 10:59:56.692 DEBUG:Registering mod PA_Esme
12/27/24 10:59:56.692 DEBUG:Queueing mod PA_Esme, fullyLoaded: true
12/27/24 10:59:56.692 DEBUG:finish all mod updates
12/27/24 10:59:56.692 DEBUG:Match stage panel-attack-magellan-night already fully loaded in GameBase:load()
12/27/24 10:59:56.692 DEBUG:Pushing scene EndlessGame on top of stack
12/27/24 11:00:11.364 DEBUG:P1@860: Pushing garbage for chain with 3 panels
12/27/24 11:00:12.764 DEBUG:Player 1 chain ended at 944
12/27/24 11:00:37.015 DEBUG:P1@2399: Pushing garbage for chain with 6 panels
12/27/24 11:00:38.815 DEBUG:Player 1 chain ended at 2507
12/27/24 11:00:52.966 DEBUG:P1@3356: Pushing garbage for combo with 4 panels
12/27/24 11:01:18.833 DEBUG:P1@4908: Pushing garbage for chain with 3 panels
12/27/24 11:01:20.232 DEBUG:Player 1 chain ended at 4992
12/27/24 11:01:32.382 DEBUG:P1@5721: Pushing garbage for combo with 4 panels
12/27/24 11:01:52.266 DEBUG:P1@6914: Pushing garbage for chain with 3 panels
12/27/24 11:01:53.483 DEBUG:Player 1 chain ended at 6987
12/27/24 11:02:56.950 DEBUG:P1@8290: Pushing garbage for combo with 4 panels
12/27/24 11:02:58.634 DEBUG:P1@8391: Pushing garbage for chain with 3 panels
12/27/24 11:02:59.851 DEBUG:Player 1 chain ended at 8464
12/27/24 11:03:27.733 DEBUG:P1@10137: Pushing garbage for combo with 4 panels
12/27/24 11:03:53.202 DEBUG:P1@11665: Pushing garbage for chain with 3 panels
12/27/24 11:03:54.601 DEBUG:Player 1 chain ended at 11749
12/27/24 11:04:11.418 DEBUG:P1@12758: Pushing garbage for chain with 3 panels
12/27/24 11:04:12.635 DEBUG:Player 1 chain ended at 12831
12/27/24 11:04:26.793 DEBUG:P1@13680: Pushing garbage for combo with 7 panels
12/27/24 11:04:34.893 DEBUG:P1@14166: Pushing garbage for chain with 3 panels
12/27/24 11:04:36.110 DEBUG:Player 1 chain ended at 14239
12/27/24 11:04:45.693 DEBUG:P1@14814: Pushing garbage for chain with 3 panels
12/27/24 11:04:46.910 DEBUG:Player 1 chain ended at 14887
12/27/24 11:04:54.576 DEBUG:P1@15347: Pushing garbage for chain with 3 panels
12/27/24 11:04:55.793 DEBUG:Player 1 chain ended at 15420
12/27/24 11:04:58.945 DEBUG:P1@15609: Pushing garbage for combo with 4 panels
12/27/24 11:05:45.044 DEBUG:P1@18375: Pushing garbage for chain with 3 panels
12/27/24 11:05:46.444 DEBUG:Player 1 chain ended at 18459
12/27/24 11:05:58.244 DEBUG:P1@19167: Pushing garbage for chain with 3 panels
12/27/24 11:05:59.644 DEBUG:Player 1 chain ended at 19251
12/27/24 11:07:15.327 DEBUG:P1@23792: Pushing garbage for chain with 6 panels
12/27/24 11:07:17.161 DEBUG:Player 1 chain ended at 23902
12/27/24 11:07:51.911 DEBUG:P1@25987: Pushing garbage for chain with 3 panels
12/27/24 11:07:53.345 DEBUG:Player 1 chain ended at 26073
12/27/24 11:08:01.878 DEBUG:P1@26585: Pushing garbage for combo with 4 panels
12/27/24 11:08:03.513 DEBUG:P1@26683: Pushing garbage for chain with 3 panels
12/27/24 11:08:04.730 DEBUG:Player 1 chain ended at 26756
12/27/24 11:08:07.283  INFO:client/src/scores.lua:73: attempt to compare number with nil
12/27/24 11:08:07.284  INFO:config during crash: save_replays_publicly with my name
portrait_darkness 70
popfx true
shakeIntensity 1
cardfx_scale 100
renderTelegraph true
renderAttacks true
defaultPanelsCopied false
maximizeOnStartup true
gameScaleType auto
version 048
fullscreen false
language_code EN
gameScaleFixedValue 2
theme Panel Attack Modern
panels pacci
character PA_Esme
stage __RandomStage
ranked true
inputMethod controller
windowY 55
use_music_from either
display 1
level 5
endless_speed 1
endless_difficulty 2
windowX 0
puzzle_level 5
puzzle_randomColors false
puzzle_randomFlipped false
master_volume 50
SFX_volume 50
music_volume 50
enableMenuMusic true
debug_mode false
debugShowServers false
debugShowDesignHelper false
show_fps false
activeGarbageCollectionPercent 0.2
show_ingame_infos true
danger_music_changeback_delay false
enable_analytics true
borderless false
windowHeight 997
windowWidth 1920
name brocolli

**Comment by Endaris** [comment]
Thanks for the report, should be fixed with this commit: [600210a](https://github.com/panel-attack/panel-game/commit/600210ae16e44ca535065b3e10cd4da811e84ae5)

The table in this case was correctly initialized but the parameter passed into the function was nil when it should not have been. Oversight from landing [a huge PR](https://github.com/panel-attack/panel-game/pull/564) a few days ago and I only tested Endless in modern mode, not in classic mode so I didn't catch it in advance.
