### ISSUE TITLE
Fix everything broken with spectator mode

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#6]
This would require detailed issues to be opened. Don't know when you could call spectator mode fully fixed.

As of opening this issue, it had 32 votes (most voted issue having 72)

**Comment by JamesVanBoxtel** [comment]
We should get more details on this or close it...

**Comment by AegisCrusader** [comment]
Closing because I believe we have fixed the spectator mode bugs in things such as panel-attack/panel-attack#253
