### ISSUE TITLE
Server doesn’t kick stuck rooms

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#61]
<img width="272" alt="spectate0 () Bbforky (1782) (lobby)" src="https://user-images.githubusercontent.com/8935453/141664280-c43e03f2-460a-47b0-b976-ff2b420b1de2.png">

Rarely users can get stuck in the "lobby" but in a room, or sit in a room and not play for hours.

The server should close connections if nothing has happened for multiple hours.

**Comment by AegisCrusader** [comment]
Did we fix this? I think we did at some point.
