### ISSUE TITLE
Change Icons of versions

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#63]
Change icons of alpha, beta, and stable so users can tell the difference

**Comment by JamesVanBoxtel** [comment]
What will we use for the icon images?

**Comment by JamesVanBoxtel** [comment]
Good temporary icons, curtesy of Buster. More "official" icons can come later from PACCI

![PA_Icon_Alpha](https://user-images.githubusercontent.com/8935453/166862950-ec4deaca-05ab-4061-8a95-2f17274b5206.png)
![PA_Icon_Beta](https://user-images.githubusercontent.com/8935453/166862958-bf65d039-b946-4289-9c4c-455dc1651e63.png)
![PA_Icon](https://user-images.githubusercontent.com/8935453/166862962-da19750b-5fac-4753-b003-39ef38e0209b.png)

**Comment by Endaris** [comment]
Related discussion: https://discord.com/channels/196674532491132937/854285957347147778/947353612076580924
Benched for now since alpha is retired and introducing an icon seems weird when pacci is not far away.

**Comment by Endaris** [comment]
Closing because:
1. canary release now has a pacci panel as an icon
2. the plan going forward is to use only a single auto updater for all releasestreams and have an ingame releasestream picker which makes different icons obsolete
