### ISSUE TITLE
Ghost Lobby Clickables

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#68]
After showing the leaderboard, lobby text is shifted to the left to make room for the leaderboard on the right. However, when the leaderboard is being shown, it is still possible to click to the right of where the text _used_ to be, in the empty space, and it the game will trigger whatever option it is next to. Steps to reproduce this glitch are:

1. Enter lobby
2. Use mouse to select "show leaderboard"
3. Use mouse to select any match to spectate
4. Leave the match to return to the lobby
5. Use mouse to select "show leaderboard"
6. Use mouse to select "hide leaderboard"
7. Use mouse to select "show leaderboard"
8. Use mouse to click on the right of any option to perform the Ghost select

The image below shows the approximate clickable areas as a result of the glitch.
![image](https://user-images.githubusercontent.com/18148657/142508506-8800ac18-0b6f-4583-b134-fac4fd5583b3.png)

**Comment by JamesVanBoxtel** [comment]
The proper thing to do here is upgrade the leaderboard to a real click menu and not render or update the lobby while the leaderboard is showing.

**Comment by AegisCrusader** [comment]
This appears to have been fixed by panel-attack/panel-attack#293
