### ISSUE TITLE
Vsync should default to off

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#76]
It seems with various OSs + gpus + love we can't guarantee love.update to be called at 60fps always with v sync turned on, but for some reason it seems to be more consistent with vsync turned off.

This will cause missed inputs whenever it happens, and isn't very obvious to the user what's going on.

Therefore we should default vsync to off. The opposite problem IS obvious. The screen refreshing in a weird way. If that bothers the user, it will be much more obvious what to do, go turn vsync on.

We might want to have explanatory text in settings too.

**Comment by AegisCrusader** [comment]
I'm not entirely sure we should do this. If "missed input" means that  the game literally drops the input entirely, I've never encountered that. I think the cons outweigh the pros here, the screen tear can get pretty significant.

**Comment by AegisCrusader** [comment]
![image](https://user-images.githubusercontent.com/18148657/144897183-2dcafa94-b269-4a8a-b498-06aa4d58ddb8.png)
Alright, I'll take the L here.
