### ISSUE TITLE
When rapidly going from spectating one game to another things get wonky

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-game#78]
Poke: So again the bug is that if you back out of a match that ended and went to spectate another match, that the levels and board will appear on their screen and cause a strange outcome, following a freeze. Now it gets worse by attempting to spectate the actual last match of the previous match you were spectating, following up with another match that has the second player's board rise to the top and die in 1 second before kicking you out to the main menu. If you don't restart your game, this bug affects you for the duration you stay in the game

**Comment by AegisCrusader** [comment]
This needs to be clarified further

**Comment by JamesVanBoxtel** [comment]
Yes it needs investigation. But I've seen similar things when moving between rooms
