### ISSUE TITLE
Allow more customization for characters

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#8]
As of opening this issue, it had 35 votes (most voted issue having 72)

**Comment by JamesVanBoxtel** [comment]
We should get more details on this or close it... characters have a lot of customization now.

**Comment by Endaris** [comment]
DoubleBang suggested making Pop SFX customizable per character as well as fanfares (which are also character specific in Super Plexis).
I think in general one would want to look at some assets that are theme specific right now but could make sense on a per character base as well, e.g. the health bar, frame (if we start using them), potentially even the cursor.

Pop SFX/FX and Fanfares are the most sensible choices to start with though.

**Comment by Endaris** [comment]
I'm closing this for now and will add a new issue with a more specific title + description, aimed at the specifics suggested by DoubleBang.
