### ISSUE TITLE
Reduce log output

### ISSUE THREAD

**Issue by Zeimyth** [panel-attack/panel-game#84]
The codebase makes liberal use of `print` all over the place for logging. Some logs are very spammy and many of them are not necessary for typical non-debug gameplay. We should implement a logging utility to make it easier to omit some messages from the logs, and potentially remove other unnecessary logs altogether.

**Comment by AegisCrusader** [comment]
![image](https://user-images.githubusercontent.com/18148657/147695448-97529898-98f1-4cac-b19d-e185ffad9bc0.png)
Indeed

**Comment by AegisCrusader** [comment]
However I do believe that we don't need to print every time we receive an input. Perhaps we can print the whole match at the conclusion, but otherwise we don't need a whole bunch of lines with like 4 letters of inputs especially

**Comment by JamesVanBoxtel** [comment]
This is finished now. Any future logging can be cleaned up as we go.
