### ISSUE TITLE
Alpha: When spectating it appears that both stacks often start in desynced state

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#87]
Quote: Endaris

**Comment by JamesVanBoxtel** [comment]
Needs investigation if this is happening and new to alpha

**Comment by JamesVanBoxtel** [comment]
shosoul and I both looked into this, I see it randomly having once side delayed and sometimes in sync which makes since based on whom has lag.

**Comment by JamesVanBoxtel** [comment]
Endaris please let us know if you have reason to believe something broke

**Comment by Endaris** [comment]
I never realised you actually addressed me here directly, oof.
I think you implemented a fix for this at some point, causing the client to wait on the first frame for confirmation from the other client that it arrived there too or something like that and any remaining desync is purely visual or not nearly as massive (I recall this being as much as 1s from the start of actual desync)

So yeah, close this.

Edit: Yeah, in Stack.send_controls you blocked sending of controls until each sent one input, indicating full readyness
