### ISSUE TITLE
Alpha: The Start Button no longer can be used to select "Ready"

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#88]
![image](https://user-images.githubusercontent.com/18148657/149575442-5c50fd74-7f09-40ad-bfc0-87ce280a729f.png)

**Comment by JamesVanBoxtel** [comment]
I think this is fixed in latest alpha? Please confirm in next auto update.

**Comment by AegisCrusader** [comment]
I can confirm this is fixed but I can't find in what PR
