### ISSUE TITLE
Local replays have a rare chance to not save "R" values, aka gpanel buffer

### ISSUE THREAD

**Issue by AegisCrusader** [panel-attack/panel-game#89]
The reason is currently unknown. Causes the replay to crash when the player that pulls gpanels from the `R` buffer clears garbage.

**Comment by JamesVanBoxtel** [comment]
I don't think we have reproduced this yet?

**Comment by AegisCrusader** [comment]
We have no way of consistently reproducing this bug. My best theory is that there is an error or glitch occurred during the write process or something, but I have no proof of that, it's merely conjecture.

**Comment by AegisCrusader** [comment]
Closing this because newer versions of the game do not use `R` anymore, instead, they use a seed.
