### ISSUE TITLE
Prettify the user interface

### ISSUE THREAD

**Issue by LittleEndu** [panel-attack/panel-game#9]
This requires somebody to do menu art

As of opening this issue, it had 35 votes (most voted issue having 72)

**Comment by LittleEndu** [comment]
The menu also looks many times better with a simple font change. Something like "Oswald-Light" would make for a good font

**Comment by sharpobject** [comment]
Do we have any particular design in mind?

**Comment by Endaris** [comment]
The suggested 2 points, font change and menu art, have been implemented with panel-attack/panel-attack#65 and panel-attack/panel-attack#98, so I'm closing this. For further graphics changes we should consider and plan them in the context of PACCI.
