### ISSUE TITLE
Try Again option for puzzle mode

### ISSUE THREAD

**Issue by MizunoKetsuban** [panel-attack/panel-game#96]
In previous versions, if you failed a puzzle you were automatically kicked out to the menu. In the current alpha, if you failed a puzzle you were locked in until you finish the set. All I'm requesting here is an option to choose which happens at the lose screen, even if it's as simple as A for yes and B for no.

**Comment by AegisCrusader** [comment]
So in alpha it doesn't kick you out to the main menu anymore, right?

**Comment by JamesVanBoxtel** [comment]
What do you mean locked in? You can press start and then b to quit

**Comment by MizunoKetsuban** [comment]
The point is that this isn't communicated to the player. The pause screen doesn't mention this, for one.

**Comment by JamesVanBoxtel** [comment]
Yeah I think on screen controls need to be shown throughout the whole game, especially in transition spots and pause

**Comment by JamesVanBoxtel** [comment]
Mix I'm thinking we should close this and use this more descriptive issue.

Thoughts
https://github.com/panel-attack/panel-game/issues/180
