### ISSUE TITLE
Alpha: Panels do not use their popping state when losing in puzzle mode

### ISSUE THREAD

**Issue by Kurtupo** [panel-attack/panel-game#99]
When losing in puzzle mode, panels currently do not go into their "popping face" like they should.
Currently, they instead remain in their default sprite.

**Comment by JamesVanBoxtel** [comment]
We should actually probably discuss what we want to do here. In TA, they pop, then dissolve and you get a game over screen. Thats not very useable for seeing what went wrong in my opinion. Maybe we should do something that still lets you see the panels clearly?

**Comment by Endaris** [comment]
I think it's better to keep them as they are as it makes it easier to reflect on what happened or what you ended up with. In the end it's just one way to indicate failure and I think SFX and the "You lose" message are sufficient although the latter could be more prominent in my opinion.

Additionally, the internal handling for puzzle's win and lose state is completely detached from the rest of the engine, making the implementation of this suggestion extremely difficult without moving entire mountain ranges. Traditionally, to get panels into popping state, we want to lose but having the stack go game over completely breaks puzzles as of now (you can no longer lose or win the puzzle after going game over).

**Comment by JamesVanBoxtel** [comment]
Yeah I think we can make it look better. But using the popping frame makes it hard to read.

**Comment by Endaris** [comment]
Accidently implemented this when rewriting a good part of how matches work.
